#install.packages("languageserver")
#install.packages("sf")
#install.packages("rlang")
#install.packages("stringi")
#install.packages("workerexthost") 
#library(geovol)
#detach(geovol, unload = TRUE)
#search()
#source("./functions.R")
#print ("hello world")
#R.home("bin")
#library(sf)

#libPaths()
#install.packages("jsonlite")
#install.packages("readr")
#install.packages("data.table")
#install.packages("zoo")
#install.packages("pdftools")
#install.packages("tesseract")
#install.packages("IRkernel")